The fork2
tiagobento/drools-wb pull request #1
Opened 2021-03-26 22:26 UTC by treblereel

KOGITO-4065: Make sure that SceSim Editor compiles with removed modules from errai/appformer

2021-03-30 11:03 UTC, caponetto requested changes

2021-03-30 11:03 UTC, caponetto commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/java/org/drools/workbench/screens/scenariosimulation/webapp/client/editor/DMNDiagramEditorActivity.java
> +    public static final String ID = "DMNDiagramEditor";
```suggestion
    public static final String ID = "ScenarioSimulationEditor";
```
Please set `ScenarioSimulationEditor`as ID.

2021-03-30 11:03 UTC, caponetto commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/java/org/drools/workbench/screens/scenariosimulation/webapp/client/editor/DMNDiagramEditorActivity.java
> +public class DMNDiagramEditorActivity extends AbstractActivity implements EditorActivity {
```suggestion
public class ScenarioSimulationEditorActivity extends AbstractActivity implements EditorActivity {
```
Please rename this class.

2021-03-30 11:47 UTC, caponetto commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/webapp/test.html
> +            window.frames.editorFrame.contentWindow.gwtEditorBeans.get("DMNDiagramEditor").get().setContent("","");
```suggestion
            window.frames.editorFrame.contentWindow.gwtEditorBeans.get("ScenarioSimulationEditor").get().setContent("","");
```
Please update this ID and others below (lines 30 and 42)

2021-03-30 12:47 UTC, treblereel commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/java/org/drools/workbench/screens/scenariosimulation/webapp/client/editor/DMNDiagramEditorActivity.java
> +    public static final String ID = "DMNDiagramEditor";
Yeap, sure

2021-03-30 12:47 UTC, treblereel commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/java/org/drools/workbench/screens/scenariosimulation/webapp/client/editor/DMNDiagramEditorActivity.java
> +public class DMNDiagramEditorActivity extends AbstractActivity implements EditorActivity {
ok

2021-03-31 10:19 UTC, caponetto commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/pom.xml
> +    </dependency>
Please remove this duplicated dependency. We already have this one on line 74.

2021-03-31 10:24 UTC, caponetto commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/pom.xml
> +    </dependency>
Please remove this duplicated dependency. We already have this one on line 42.

2021-03-31 10:56 UTC, caponetto commented
I'm not sure the reason but I had to rename the package of the `SortTable` class. Otherwise, I can't compile.
```diff
-package org.drools.workbench.services.verifier.plugin.client.api;
+package org.guvnor.common.services.shared.exceptions;
```
Maybe something with the merge after integrating https://github.com/tiagobento/drools-wb/pull/1/commits/21178fbf4eeaf5986943df34c44eeb2e63b6dbe0?

2021-03-31 11:03 UTC, caponetto commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/webapp/test.html
> +                        d.setAttribute('download', "diagram.sce");
```suggestion
                        d.setAttribute('download', "diagram.scesim");
```
Please fix the extension name.

2021-03-31 11:07 UTC, caponetto commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/pom.xml
> +          <style>PRETTY</style>
Please remove this duplicated tag. Line 416 already sets it.

2021-04-01 16:28 UTC, caponetto approved these changes

2021-04-01 17:19 UTC, merged